config/routes.rb
BiblioLibre::Application.routes.draw do

  resources :posts
  resources :hearts, only: :create

  get '/diab_portada' => 'diab#index', as: 'diab'

  get 'tags/:tag' => 'posts#comunidad', as: :tag
  get '/posts/comunidad' => 'posts#comunidad'
  get '/comunidad' => 'posts#comunidad', as: 'comunidad'
  get '/noticias/1' => 'biblio_libre#noticia1', :as => 'noticia1'
  get '/noticias/2' => 'biblio_libre#noticia2', :as => 'noticia2'
  get '/noticias/3' => 'biblio_libre#noticia3', :as => 'noticia3'
  get '/noticias/4' => 'biblio_libre#noticia4', :as => 'noticia4'
  get '/noticias/5' => 'biblio_libre#noticia5', :as => 'noticia5'
  get '/noticias/:id' => 'posts#noticia'
  get '/galeria1' => 'biblio_libre#galeria1'
  get '/galeria2' => 'biblio_libre#galeria2'
  get '/galeria3' => 'biblio_libre#galeria3'
  get '/galeria4' => 'biblio_libre#galeria4'
  get '/galeria5' => 'biblio_libre#galeria5'
  get '/galeria6' => 'biblio_libre#galeria6'
  get '/galeria7' => 'biblio_libre#galeria7'
  get '/sociales' => 'biblio_libre#sociales'
  get '/batalla' => 'biblio_libre#batalla'
  get '/resultados' => 'biblio_libre#resultados'
  get '/about' => 'biblio_libre#about' # Borrar
  get '/about/manifest' => 'about#manifest', :as => 'manifest'
  get '/galerias' => 'biblio_libre#galerias'
  get '/comunidad' => 'biblio_libre#comunidad'
  get '/about/faqs' => 'about#faqs'
  get '/about/equipo' => 'about#equipo'
  get '/about/normas' => 'about#normas'
  get '/about/donaciones' => 'about#donaciones'
  get '/bibliocabinas' => 'biblio_libre#bibliocabinas'

  get '/diab' => 'biblio_libre#diab'
  post '/participa_diab' => 'diab#participa'

  post '/tinymce_assets' => 'biblio_libre#uploads'

  get '/massive_load' => 'biblio_libre#massive_load', :as => 'massive_load'
  post '/proccess_massive_load' => 'biblio_libre#proccess_massive_load', :as => 'proccess_massive_load'

  get '/vota/:battle_id/:book' => 'battles#vote'

  get '/books/export' => 'books#export_data'

  # get '/zohoverify/verifyforzoho.html', to: redirect('/assets/verifyforzoho.html')

  devise_for :users

  resources :releases
  resources :findings
  resources :books

  resources :battles

  get '/books/:code/ajax' => 'books#show_by_code', as: 'books_ajax'

  get '/check_code' => 'books#check_code'
  get '/new_book_and_finding/:code'  => 'books#new_book_and_finding', as: 'new_book_and_finding'
  get '/new_finding_with_code/:code' => 'findings#new_with_code', as: 'new_finding_with_code'


  get '/libera' => 'books#new_book_and_release', as: 'new_book_and_release'
  get '/new_book_and_release' => 'books#new_book_and_release'
  post '/printables' => 'books#printables', as: 'printables'
  post '/printables_diab' => 'diab#printables', as: 'printables_diab'
  get '/generate_pdf/:code' => 'books#generate_pdf', as: 'generate_pdf'

  get '/map' => 'findings#map', as: 'findings_map'

  get '/bibliotecas' => 'biblio_libre#bibliotecas', as: 'bibliotecas'
  get '/faq' => 'biblio_libre#faq', as: 'faq'
  get '/que_es' => 'biblio_libre#que_es', as: 'que_es'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
	match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'invitanos' => 'contact#invitanos', :as => 'invitanos', :via => :get
  match 'invitanos' => 'contact#invitanos_create', :as => 'invitanos', :via => :post

  match 'dona' => 'contact#dona', :as => 'dona', :via => :get
  match 'dona' => 'contact#dona_create', :as => 'dona', :via => :post

  match 'concurso' => 'contact#concurso', :as => 'concurso', :via => :get
  match 'concurso' => 'contact#concurso_create', :as => 'concurso', :via => :post

  get '/QR' => 'biblio_libre#index'
  get '/qr' => 'biblio_libre#index'

  get '/emails' => 'findings#emails'

  get '/nuevo_home' => 'biblio_libre#index_nuevo'

  get '/instrucciones' => 'biblio_libre#instrucciones', :as => 'instrucciones'

  get '/colaboradores' => 'biblio_libre#colaboradores', :as => 'colaboradores'

  get '/donativos' => 'biblio_libre#donativos', :as => 'donativos'

  get '/bibliolibre' => 'biblio_libre#index_nuevo', as: 'portada'

  root to: 'biblio_libre#index_nuevo'
  # root to: 'diab#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                         :integer          not null, primary key
#  title                      :string(255)
#  content                    :text
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  picture_file_name          :string(255)
#  picture_content_type       :string(255)
#  picture_file_size          :integer
#  picture_updated_at         :datetime
#  small_picture_file_name    :string(255)
#  small_picture_content_type :string(255)
#  small_picture_file_size    :integer
#  small_picture_updated_at   :datetime
#  description                :text
#  kind                       :string(255)
#  bajada                     :text
#  autor                      :text
#

class Post < ActiveRecord::Base
  extend FriendlyId

  attr_accessible :content, :description, :title, :picture, :small_picture, :tag_list, :kind, :bajada, :autor
  acts_as_taggable
  acts_as_votable
  has_many :hearts

  friendly_id :title, use: [:slugged, :history]

  has_attached_file :picture, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>',
    large: '1170x390'
  }

  has_attached_file :small_picture, styles: {
    thumb: '160x111>',
    face: '320x222',
    square: '200x200>',
    medium: '300x300>'
  }

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :small_picture, :content_type => /\Aimage\/.*\Z/

  def self.byKind kind, n=1
    if n == 1
      Post.where(kind: kind).order('created_at DESC').first
    else
      Post.where(kind: kind).order('created_at DESC').take(n)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:noticia, :show, :comunidad]

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
    @posts = Post.all
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
    end
  end

   def comunidad
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
    @posts = Post.all
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end

    @post = Post.find(params[:id])

    @last_posts = Post.select('*').where('id != ?', @post.id).where("kind LIKE 'comunidad 1' or kind LIKE 'comunidad 2' or kind LIKE 'comunidad 1'").limit(6).order('id desc')
    @columns = Post.select('*').where('id != ?', @post.id).where("kind LIKE 'columna'").limit(6).order('id desc')

    @og_description = @post.description
    @og_title = @post.title

    if @post.small_picture.url(:face) != "/small_pictures/face/missing.png"
      @og_image = @post.small_picture.url(:face)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def noticia
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    render layout: 'admin'
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])

    render layout: 'admin'
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, 'Descripción corta' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :bajada, 'Bajada de título' %><br />
    <%= f.text_area :bajada %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => 'tinymce tiny', :rows => 40, :cols => 120 %>
  </div>
 <div class="field">
    <%= f.label :tag_list, "Tags (separadas por coma)" %><br />
    <%= f.text_field :tag_list %>
  </div>
   <div class="field">
    <%= f.label :kind %><br />
    <%= f.select :kind, ["liberación", "noticia", "comunidad 1", "comunidad 2", "columna", "comunidad 3", "especial", "otro" ] %>
  </div>
  <div class="field">
    <%= f.label :picture, 'Foto: ' %> <%= f.file_field :picture %>
  </div>

  <div class="field">
    <%= f.label :small_picture, 'Foto chica: ' %> <%= f.file_field :small_picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/comunidad.erb
<div class="span10 offset1">
	<div class="row">
		<h2 style="color:#727272">
		Todas las entradas
		</h2>
	</div>
	<br><br>
		<% @posts.each do |post| %>
		<div class="row">
			<div class="span1 offset1">
				<%= link_to (image_tag post.small_picture.url(:thumb)), post %>
			</div>
			<div class="span4" style="margin-left: 8px">
				<%= link_to (post.title), post %>
				<p style="font-size:12px"><%= post.description %></p>
			</div>
		</div>
		<br><br>
		<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<%= link_to 'New Post', new_post_path , { class: "btn btn-primary" } %>

<br />

<table class="table table-striped table-bordered">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join (', ') %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/noticia.html.erb
<div class="row">
	<div class="span12" style="text-align: center;">
		<%= image_tag @post.picture.url(:large) %>
	</div>
</div>
<br />
<div class="row">
	<div class="span12">
		<div class="well">
		 	<h2><%= @post.title %></h2>
		 	<br />
			<%=raw  @post.content %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<% if @post.kind == "columna" %>
	<div class="row">
		<div class="span6 offset1">
			 	<h2 style="color:#727272"><%= @post.title %></h2>
			 	<br />
			 	<%=raw @post.bajada %>
			 	<br>
			 	<div class="row">
			 		<div class="span1">
			 			<%= image_tag @post.small_picture.url(:thumb) %>
			 		</div>
			 		<div class="span3">
			 			<p style="color:#fff">.</p>
			 			<p><small><%= @post.autor %></small></p>
			 		</div>
			 	</div>
			 	<br><br>
				<%=raw  @post.content %>
		</div>
		<div class="span4 offset1">
			<% if @post.picture.url(:large) != "/pictures/large/missing.png" %>
			 	<%= image_tag @post.picture.url(:large) %>
			<% end %>
			<br><br><br>
			<h3> Más columnas </h3>
			<br>

			<% @columns.each do |column| %>
				<div class="row">
					<div class="span1">
						<%= link_to (image_tag column.picture.url(:thumb)), column %>
					</div>
					<div class="span2" style="margin-left: 8px">
						<%= link_to (column.title), column %>
					</div>
				</div>
				<br />
			<% end %>


			</div>
		</div>
	<br>
	<div class="row">
		<div class="span6 offset1">
			<p>
			Etiquetas:
			<%= raw @post.tag_list.map { |t| link_to t, tag_path(t), {:style=>'color:#ff9900;', :class => "css_class"}}.join (', ') %>
			</p>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="span6 offset1">
			<hr />
				<div class="fb-like" data-href="<%= request.original_url %>" data-layout="standard" data-action="recommend" data-show-faces="true" data-share="true"></div>
			<hr />
		</div>
	</div>

	<div class="row">
		<div class="span6 offset1">
			<div class="fb-comments" data-href="<%= request.base_url + '/posts/' + @post.id.to_s %>" data-numposts="5" data-colorscheme="light"></div>
		</div>
	</div>

<% elsif (@post.kind == "comunidad 1" or @post.kind == "comunidad 2" or @post.kind == "comunidad 3") %>
	<div class="row">
		<div class="span6 offset1">
			 	<h2 style="color:#727272"><%= @post.title %></h2>
			 	<br />
				<%=raw  @post.content %>
		</div>
		<div class="span4 offset1">
			<% if @post.picture.url(:large) != "/pictures/large/missing.png" %>
			 	<%= image_tag @post.picture.url(:large) %>
			<% end %>
			<br><br><br>
			<h3> Más comunidad </h3>
			<br>
			<% @last_posts.each do |last_post| %>
				<div class="row">
					<div class="span1">
						<%= link_to (image_tag last_post.small_picture.url(:thumb)), last_post %>
					</div>
					<div class="span2" style="margin-left: 8px">
						<%= link_to (last_post.title), last_post %>
					</div>
				</div>
				<br />
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="span6 offset1">
			<p>
			Etiquetas:
			<%= raw @post.tag_list.map { |t| link_to t, tag_path(t), {:style=>'color:#ff9900;', :class => "css_class"}}.join (', ') %>
			</p>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="span6 offset1">
			<hr />
				<div class="fb-like" data-href="<%= request.original_url %>" data-layout="standard" data-action="recommend" data-show-faces="true" data-share="true"></div>
			<hr />
		</div>
	</div>

	<div class="row">
		<div class="span6 offset1">
			<div class="fb-comments" data-href="<%= request.base_url + '/posts/' + @post.id.to_s %>" data-numposts="5" data-colorscheme="light"></div>
		</div>
	</div>

<% elsif @post.kind == "especial" %>
	<div class="row">
		<div class="span6 offset1">
			<h2 style="color:#727272"><%= @post.title %></h2>
			<br />
		</div>
	</div>
	<div class="row">
		<div class="span6 offset1">
		<%= image_tag @post.picture %>
	</div>
	</div>
	<br>
	<div class="row">
		<div class="span6 offset1">
			<hr />
				<div class="fb-like" data-href="<%= request.original_url %>" data-layout="standard" data-action="recommend" data-show-faces="true" data-share="true"></div>
			<hr />
		</div>
	</div>

	<div class="row">
		<div class="span6 offset1">
			<div class="fb-comments" data-href="<%= request.base_url + '/posts/' + @post.id.to_s %>" data-numposts="5" data-colorscheme="light"></div>
		</div>
	</div>

<% else %>
	<div class="row">
		<div class="span6 offset1">
			 	<h2 style="color:#727272"><%= @post.title %></h2>
			 	<br />
				<%=raw  @post.content %>
		</div>
		<div class="span4 offset1">
			<% if @post.picture.url(:large) != "/pictures/large/missing.png" %>
			 	<%= image_tag @post.picture.url(:large) %>
			<% end %>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="span6 offset1">
			<p>
			Etiquetas:
			<%= raw @post.tag_list.map { |t| link_to t, tag_path(t), {:style=>'color:#ff9900;', :class => "css_class"}}.join (', ') %>
			</p>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="span6 offset1">
			<hr />
				<div class="fb-like" data-href="<%= request.original_url %>" data-layout="standard" data-action="recommend" data-show-faces="true" data-share="true"></div>
			<hr />
		</div>
	</div>

	<div class="row">
		<div class="span11 offset1">
			<div class="fb-comments-unloaded" data-href="<%= request.base_url + '/posts/' + @post.id.to_s %>" data-numposts="5" data-colorscheme="light"></div>
		</div>
	</div>
<% end %>