config/routes.rb
BiblioLibre::Application.routes.draw do

  resources :posts
  resources :hearts, only: :create

  get '/diab_portada' => 'diab#index', as: 'diab'

  get 'tags/:tag' => 'posts#comunidad', as: :tag
  get '/posts/comunidad' => 'posts#comunidad'
  get '/comunidad' => 'posts#comunidad', as: 'comunidad'
  get '/noticias/1' => 'biblio_libre#noticia1', :as => 'noticia1'
  get '/noticias/2' => 'biblio_libre#noticia2', :as => 'noticia2'
  get '/noticias/3' => 'biblio_libre#noticia3', :as => 'noticia3'
  get '/noticias/4' => 'biblio_libre#noticia4', :as => 'noticia4'
  get '/noticias/5' => 'biblio_libre#noticia5', :as => 'noticia5'
  get '/noticias/:id' => 'posts#noticia'
  get '/galeria1' => 'biblio_libre#galeria1'
  get '/galeria2' => 'biblio_libre#galeria2'
  get '/galeria3' => 'biblio_libre#galeria3'
  get '/galeria4' => 'biblio_libre#galeria4'
  get '/galeria5' => 'biblio_libre#galeria5'
  get '/galeria6' => 'biblio_libre#galeria6'
  get '/galeria7' => 'biblio_libre#galeria7'
  get '/sociales' => 'biblio_libre#sociales'
  get '/batalla' => 'biblio_libre#batalla'
  get '/resultados' => 'biblio_libre#resultados'
  get '/about' => 'biblio_libre#about' # Borrar
  get '/about/manifest' => 'about#manifest', :as => 'manifest'
  get '/galerias' => 'biblio_libre#galerias'
  get '/comunidad' => 'biblio_libre#comunidad'
  get '/about/faqs' => 'about#faqs'
  get '/about/equipo' => 'about#equipo'
  get '/about/normas' => 'about#normas'
  get '/about/donaciones' => 'about#donaciones'
  get '/bibliocabinas' => 'biblio_libre#bibliocabinas'

  get '/diab' => 'biblio_libre#diab'
  post '/participa_diab' => 'diab#participa'

  post '/tinymce_assets' => 'biblio_libre#uploads'

  get '/massive_load' => 'biblio_libre#massive_load', :as => 'massive_load'
  post '/proccess_massive_load' => 'biblio_libre#proccess_massive_load', :as => 'proccess_massive_load'

  get '/vota/:battle_id/:book' => 'battles#vote'

  get '/books/export' => 'books#export_data'

  # get '/zohoverify/verifyforzoho.html', to: redirect('/assets/verifyforzoho.html')

  devise_for :users

  resources :releases
  resources :findings
  resources :books

  resources :battles

  get '/books/:code/ajax' => 'books#show_by_code', as: 'books_ajax'

  get '/check_code' => 'books#check_code'
  get '/new_book_and_finding/:code'  => 'books#new_book_and_finding', as: 'new_book_and_finding'
  get '/new_finding_with_code/:code' => 'findings#new_with_code', as: 'new_finding_with_code'


  get '/libera' => 'books#new_book_and_release', as: 'new_book_and_release'
  get '/new_book_and_release' => 'books#new_book_and_release'
  post '/printables' => 'books#printables', as: 'printables'
  post '/printables_diab' => 'diab#printables', as: 'printables_diab'
  get '/generate_pdf/:code' => 'books#generate_pdf', as: 'generate_pdf'

  get '/map' => 'findings#map', as: 'findings_map'

  get '/bibliotecas' => 'biblio_libre#bibliotecas', as: 'bibliotecas'
  get '/faq' => 'biblio_libre#faq', as: 'faq'
  get '/que_es' => 'biblio_libre#que_es', as: 'que_es'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
	match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'invitanos' => 'contact#invitanos', :as => 'invitanos', :via => :get
  match 'invitanos' => 'contact#invitanos_create', :as => 'invitanos', :via => :post

  match 'dona' => 'contact#dona', :as => 'dona', :via => :get
  match 'dona' => 'contact#dona_create', :as => 'dona', :via => :post

  match 'concurso' => 'contact#concurso', :as => 'concurso', :via => :get
  match 'concurso' => 'contact#concurso_create', :as => 'concurso', :via => :post

  get '/QR' => 'biblio_libre#index'
  get '/qr' => 'biblio_libre#index'

  get '/emails' => 'findings#emails'

  get '/nuevo_home' => 'biblio_libre#index_nuevo'

  get '/instrucciones' => 'biblio_libre#instrucciones', :as => 'instrucciones'

  get '/colaboradores' => 'biblio_libre#colaboradores', :as => 'colaboradores'

  get '/donativos' => 'biblio_libre#donativos', :as => 'donativos'

  get '/bibliolibre' => 'biblio_libre#index_nuevo', as: 'portada'

  root to: 'biblio_libre#index_nuevo'
  # root to: 'diab#index'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def faqs
	end
	def equipo
	end
end

app/views/about/_menu.html.erb
<div class="span2 offset1">
	<p style="color: #ffffff">.</p>
	<ul class="nav nav-pills nav-stacked">
		<%= nav_link 'Manifiesto', manifest_path %>
		<%= nav_link 'Normas', about_normas_path %>
		<%= nav_link 'Donaciones', about_donaciones_path %>
		<%= nav_link 'Equipo', about_equipo_path %>
		<%= nav_link 'Preguntas Frecuentes', about_faqs_path %>
		<%= nav_link 'Contacto', contact_path %>
	</ul>
</div>

app/views/about/donaciones.html.erb
<div class="row">
	<%= render 'menu' %>
	<div class="span9">
	<h2>Donaciones de libros.</h2>

	<p>Nos encantan las donaciones. No solo porque quien lo hace lo hace de corazón, sino porque además son libros que permiten ampliar la variedad de textos de nuestra biblioteca. Por eso, si en tu hogar cuentas con libros que desees dar de baja y piensas que alguien más les podría sacar provecho, o si formas parte de alguna institución que desea donar algunos ejemplares, no lo dudes y contáctanos. Puedes venir a dejarlos personalmente o bien, podemos ir a retirarlos.</p>

	<p>Hemos elaborado algunas consideraciones para tomar en cuenta al momento de donar:</p>

	<ul>
		<li>Los libros deben estar en buen estado.</li>
		<li>Deben ser originales.</li>
		<li>No deben ser fotocopias, cuadernos y/o apuntes de estudios universitarios.</li>
	</ul>
	<p>Recomendamos revisar las cajas antes de ser entregadas, pues nos hemos encontrado con varios objetos personales y no queremos que te angusties por la pérdida.</p>
	</div>
</div>

app/views/about/equipo.html.erb
<div class="row">
	<%= render 'menu' %>
	<div class="span9">
		<div class="row">
			<div class="span2 offset1">
				<img src="https://s3.amazonaws.com/bibliorock/Equipo-1.png" widht="150" height="150" alt="" />
			</div>
			<div class="span5">
				<h3 style="color:#727272">
					Carlos Mancilla Cofré
				</h3>
				<br>
				<p>
					Chileno, 25 años. Cofundador de Cátedras Libres y la Biblioteca Libre. Ingeniero Civil Eléctrico de la Universidad de Chile. Le gusta el fútbol. Simpatizante de Colo-Colo. Desde hace mucho tiempo que está ligado a proyectos que se esfuerzan por disminuir la tremenda brecha educacional que existe en nuestro país.
				</p>
			</div>
		</div>
		<br><br><br>
		<div class="row">
			<div class="span2 offset1">
				<img src="https://s3.amazonaws.com/bibliorock/Equipo-2.png" widht="150" height="150" alt="" />
			</div>
			<div class="span5">
				<h3 style="color:#727272">
					Diego Ramírez Hizaut
				</h3>
				<br>
				<p>
					Chileno, 25 años. Emprendedor en Start-Up Chile, cofundador de Cátedras Libres y La Biblioteca Libre, estudiante de Ingeniería Comercial en la U. de Chile y eterno voluntario por causas sociales.
				</p>
			</div>
		</div>
		<br><br><br>
		<div class="row">
			<div class="span2 offset1">
				<img src="https://s3.amazonaws.com/bibliorock/Mr_Morton-60.jpg" alt="" widht="150" height="150" />
			</div>
			<div class="span5">
				<h3 style="color:#727272">
					Raúl Muñoz Muñoz
				</h3>
				<br>
			</div>
		</div>
		<br><br><br>
		<div class="row">
			<div class="span2 offset1">
				<img src="https://s3.amazonaws.com/bibliorock/Equipo-3.png" widht="150" height="150" alt="" />
			</div>
			<div class="span5">
				<h3 style="color:#727272">
					Juan Carlos Piña
				</h3>
				<br>
			</div>
		</div>
	</div>
</div>

app/views/about/faqs.html.erb
<div class="row">
	<%= render 'menu' %>
	<br>
	<div class="span7 offset1 well negro center"
	<dl>
		<h2> Preguntas Frecuentes </h2>
		<br><br>
		<a href='javascript:void(0)' onclick="toggle_visibility('p1');"><p><strong>¿De qué se trata La Biblioteca Libre?</strong></p></a>
		<div id="p1" style="display:none">En pocas palabras: encuentra, lee y comparte.</div>
		<br>

		<a href='javascript:void(0)' onclick="toggle_visibility('p2');"><p><strong>¿Pueden resumir cómo funciona La Biblioteca Libre en unos pocos pasos?</strong></p></a>
		<div id="p2" style="display:none">Cada libro que encuentres y que tenga un código y adhesivo de La Biblioteca Libre tienes que registrarlo en esta página web. Así sabremos que está en buenas manos y está siendo usado. En este proceso es muy importante compartirlo cuando lo hayas terminado, para que nadie se quede sin la oportunidad de leerlo.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p3');"><p><strong>¿Cómo registro un libro de La Biblioteca Libre que encontré o me pasaron?</strong></p></a>
		<div id="p3" style="display:none">En esta página haz clic en el botón ‘Registra’ y completa los datos.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p4');"><p><strong>Encontré un libro de La Biblioteca Libre. ¿Qué tengo que hacer?</strong></p></a>
		<div id="p4" style="display:none">Léelo. Luego, compártelo.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p5');"><p><strong>¿Dónde encuentro más libros?</strong></p></a>
		<div id="p5" style="display:none">Nos puedes visitar todo el año en nuestra biblioteca del barrio Bellas Artes (Santo Domingo 588, 2º piso), o encontrarnos en las Liberaciones de Libros que organizamos, las que tienen un funcionamiento itinerante en la ciudad de Santiago.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p6');"><p><strong>¿A qué se refieren con liberar un libro?</strong></p></a>
		<div id="p6" style="display:none">En La Biblioteca Libre creemos que cada libro tiene su magia, pero que se pierde si nadie lo lee. Por eso los liberamos, para que quien los encuentre pueda leerlos y disfrutarlos. La verdadera magia está en compartir.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p7');"><p><strong>¿Qué hago si se me pierde un libro?</strong></p></a>
		<div id="p7" style="display:none">Mala noticia… Bueno, una lástima. No te preocupes, no quedarás en la lista negra. Más cuidado para la próxima. Al menos otra persona lo estará aprovechando.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p8');"><p><strong>¿Qué hago si el código no venía en el libro?</strong></p></a>
		<div id="p8" style="display:none">Ingrésalo como una liberación tuya. Para eso tienes que hacer clic en el botón ‘Libera’ y llenar los campos necesarios. Recuerda compartirlo cuando lo hayas terminado.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p9');"><p><strong>¿Puedo poner en circulación mis libros?</strong></p></a>
		<div id="p9" style="display:none">Por supuesto. Para eso tienes que hacer clic en el botón ‘Libera’ y llenar los campos necesarios. Luego, compártelos con una persona a la que le puedan interesar los libros. También puedes llevarlos a nuestras Liberaciones de Libros.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p10');"><p><strong>¿Tengo que leer un libro antes de liberarlo?</strong></p></a>
		<div id="p10" style="display:none">Sólo si tú quieres.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p11');"><p><strong>¿Cómo lo hago para encontrar un libro que hace tiempo estoy buscando?</strong></p></a>
		<div id="p11" style="display:none">No existe un catálogo de los libros que tenemos. Como en las Liberaciones se producen muchos intercambiamos, no es posible tener toda la información al instante.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p12');"><p><strong>¿Qué pasa si me quedo con el libro y no lo comparto?</strong></p></a>
		<div id="p12" style="display:none">Mala idea. Nos gusta confiar en la gente, por lo que esperamos que eso no pase. No nos decepciones.</div>
		<br> 

		<a href='javascript:void(0)' onclick="toggle_visibility('p13');"><p><strong>¿Cómo le paso el libro a otra persona? ¿Dónde? ¿A quién? ¿Qué le digo?</strong></p></a>
		<div id="p13" style="display:none">Revisa que tenga el código. Después, busca a una persona especial para ti a la cual le pueda interesar el libro. Posteriormente, cuéntale sobre esta genial iniciativa y recuérdale que tiene que registrar el libro para que nosotros nos enteremos de que está en buenas manos. Por último, dile que haga lo mismo que hiciste tú: compartirlo.</div>
		<br>
	</dl>
	</div>
</div>

app/views/about/manifest.html.erb
<div class="row">
	<%= render 'menu' %>
	<div class="span9">
		<h2>Manifiesto de la Biblioteca Libre</h2>

		<h3>¿Qué es la Biblioteca Libre?</h3>
		<p>La Biblioteca Libre es un proyecto que busca fomentar la lectura por medio del intercambio o trueque de libros, además de acercar las artes y la cultura a la comunidad.</p>

		<h3>¿En qué creemos?</h3>
		<p>La base que fundamenta nuestra Biblioteca es el acceso universal y transversal a la lectura, poniendo al alcance de todos material literario con gran variedad de contenido en diversas instancias como:</p>

		<ul>
			<li>Intercambio de libros, con intervenciones como la Casita de Libros, en zonas de alta afluencia de público o de interés como parques, centros comerciales, centros culturales y colegios, entre otros.</li>
			<li>Apropiarse de espacios que habitualmente tienen otra finalidad, como el proyecto Bibliocabinas en que empleamos las cabinas telefónicas en desuso de la ciudad de Santiago para elaborar bibliotecas de calle, o Bibliotaxi, que invitaba a leer o intercambiar libros mientras se viajaba en taxi.</li>
			<li>Venta de libros sin IVA.</li>
			<li>Biblioteca física ubicada en Santo Domingo #588, segundo piso, pensada como casa matriz de la Biblioteca Libre y un lugar de encuentro para lectores.</li>
			<li>Fomento lector a través actividades como concursos, reseñas literarias e historias de libros que han sido encontrados en nuestra Biblioteca por medio de nuestro sitio web.</li>
			<li>Gestión de donaciones de libros para armar bibliotecas en colegios vulnerables u otras causas sociales.</li>
		</ul>

		<p>De igual forma, creemos en la solidaridad de quienes participan en cada una de estas instancias, pues el acto de dejar un libro en nuestra biblioteca implica pensar en el otro, dejando un tesoro oculto que otra alma puede descubrir para encantarse con la lectura.</p>
	</div>
</div>

app/views/about/normas.html.erb
<div class="row">
	<%= render 'menu' %>
	<div class="span9">
		<h2>Normas de intercambio y donaciones en La Biblioteca Libre</h2>

		<p>Intercambiar un libro es un acto de empatía. Es entender que hay un otro que puede necesitar o interesarse por un libro que tal vez yo tengo. Por eso te invitamos, paradójicamente, a pensar en tí antes de intercambiar el libro y hacerte estas preguntas: ¿Te gustaría encontrar un libro de esta temática? ¿Estarías dispuesto a cambiar este libro por uno en mal estado? Si haces este ejercicio antes de venir a intercambiar, tu experiencia y la de los demás mejorará considerablemente.</p>

		<p>La Biblioteca Libre es un proyecto que busca fomentar la lectura, por medio del intercambio o trueque de libros, además de acercar las artes y la cultura a la comunidad. Para que el propósito de nuestra biblioteca se cumpla, hemos establecido algunas normas que apuntan al estado, tipo de libro que se entrega y las cantidades a intercambiar, entre otros aspectos.</p>

		<p>Para los intercambios habituales en nuestra biblioteca o en las actividades como la Casita de Libros, las normas son las siguientes:</p>

		<ol>
		<li>El libro que deseas intercambiar debe estar en muy buen estado, es decir, no debe: tener hojas sueltas, tapas y lomo despegado, haber estado mojado, estar manchado o contar con rayones en su portada o en el interior que dificulten su lectura. Si el libro cuenta con dedicatorias, algunos subrayados o nombres de personas en una de sus páginas, no es limitante para que sea objeto de cambio.
		Hemos establecido esta norma pues queremos que la experiencia entre nuestros biblioamigos sea grata. De esta manera, nos aseguramos que los ejemplares que ustedes hallen en la biblioteca sean dignos de refugiarse en sus manos. Además, nuestra biblioteca no realiza restauraciones de libros, por lo tanto, por muy interesante que sea el libro, si no está en buenas condiciones, es mejor abstenerse.</li>

		<li>No debe formar parte de colecciones escolares antiguas como: Centro Gráfico, Ercilla, Zig Zag, Colicheuque, Soluciones Escolares o Icarito, entre otras publicaciones antiguas que venían con revistas o diarios.

		En los comienzos de la biblioteca fuimos flexibles y los recibimos, sin embargo, llegaron demasiados y no había circulación. Es decir, nos llegaban muchos, pero no había lectores interesados en aquellas ediciones. Si bien estas colecciones poseen obras clásicas de la literatura universal, su misma edición y formato (textos mucho más breves y de letra pequeña) hacen que hoy no sean valorados. Como biblioteca quisimos darles una segunda oportunidad, pero por capacidad y por mantener la pluralidad no podemos seguir albergándolos.</li>

		<li>Debe ser original. En la Biblioteca libre queremos acercar la lectura a las personas, sin embargo, creemos que ese objetivo debe cumplirse respetando los derechos de autor y la propiedad intelectual, pues sin el trabajo que realizan los escritores, no podríamos disfrutar de la existencia de obras que han llenado nuestra mente con teorías, personajes y lugares sin igual. Como valoramos todo el trabajo del autor, así como también el trabajo editorial que hay detrás (ya sea en diseño, diagramación y correcciones) NO aceptamos libros piratas o “alternativos”. Por ello, y para facilitar la identificación de los falsos ejemplares, hemos elaborado esta guía.</li>

		<li>El libro que vas a entregar NO debe formar parte de estas categorías:
			<ul>
			<li>Libros religiosos o de editoriales asociadas a una iglesia o credo en particular.</li>
			<li>Biografías de años de publicación anterior al 2000. Queremos que nuestra biblioteca tenga contenido variado y actualizado.</li>
			<li>Divulgación científica como revistas de universidades, tesis o compendios de apuntes, entre otros. Si bien contamos con obras de corte académico, nuestro objetivo es llegar a la mayor cantidad de personas, sobre todo a aquellas que tienen dificultades para adquirir libros por vía tradicional, no a nichos. No queremos volvernos una biblioteca académica.</li>
			<li>Manuales de superación personal anteriores al año 2000. Por ejemplo: “Cómo dejar de ser cesante o las fórmulas para descubrir, inventar y mejorar el trabajo (sin capital)”</li>
			<li>Libros para colorear (niños y adultos) que estén pintados o rayados.</li>
			<li>Enciclopedias y diccionarios</li>
			</ul>
		</li>

		<li>Puedes intercambiar un máximo de 5 libros cada 2 semanas (10 al mes). Esta norma está pensada para evitar el aprovechamiento de algunas personas que venían a “renovar su stock” a la biblioteca para venderlos.</li>

		<li>El intercambio de libros debe ser lo más equivalente posible. Si traes un libro en inglés, puedes llevarte uno en inglés, si trajiste los de lectura escolar complementaria de tu hermanito, puedes intercambiarlo por otros textos infantiles, o si dejaste un libro de ensayos, puedes llevarte uno de ensayos. 

		Nos ocurrió mucho que todos traían los libros de sus hermanos e hijos para intercambiar. Eso hace que la biblioteca no posea un catálogo de libros variado y actualizado, sino un sin fin de listas escolares.</li>
		</ol>

		<h2>Guía para reconocer un libro pirata o “alternativo”.</h2>

		<p>Antes, una forma fácil de reconocer un libro pirata era por el tipo de papel. Solían usar el papel blanco, en vez de ese color ahuesado tan característico de los libros. Sin embargo, hoy en día la “industria de la piratería” está cada vez más sofisticada, en algunos casos el papel es del mismo tipo que aquel que poseen los originales. Por ello, hemos elaborado esta pequeña guía para que puedas reconocer cuando un libro no proviene de su fuente original y sepas de antemano si puedes o no usarlo para intercambiar o donar a nuestra biblioteca.</p>

		<ol>
			<li>La impresión no es de buena calidad. Eso genera que los párrafos sean poco legibles.</li>
			<li>Al leer el libro, o en realidad, al abrirlo, las hojas se despegan con facilidad.</li>
			<li>Páginas completas están descuadradas y corridas.</li>
			<li>Los colores de las portadas de los libros, en ocasiones, son diferentes al original. A veces más oscuros, otros más claros, pero evidencia el ahorro en la calidad de la impresión.</li>
			<li>Tapa, contratapa y lomo están corridos, no correspondiendo con los pliegues del libro.</li>
		</ol>
	</div>

</div>