config/routes.rb
BiblioLibre::Application.routes.draw do

  resources :posts
  resources :hearts, only: :create

  get '/diab_portada' => 'diab#index', as: 'diab'

  get 'tags/:tag' => 'posts#comunidad', as: :tag
  get '/posts/comunidad' => 'posts#comunidad'
  get '/comunidad' => 'posts#comunidad', as: 'comunidad'
  get '/noticias/1' => 'biblio_libre#noticia1', :as => 'noticia1'
  get '/noticias/2' => 'biblio_libre#noticia2', :as => 'noticia2'
  get '/noticias/3' => 'biblio_libre#noticia3', :as => 'noticia3'
  get '/noticias/4' => 'biblio_libre#noticia4', :as => 'noticia4'
  get '/noticias/5' => 'biblio_libre#noticia5', :as => 'noticia5'
  get '/noticias/:id' => 'posts#noticia'
  get '/galeria1' => 'biblio_libre#galeria1'
  get '/galeria2' => 'biblio_libre#galeria2'
  get '/galeria3' => 'biblio_libre#galeria3'
  get '/galeria4' => 'biblio_libre#galeria4'
  get '/galeria5' => 'biblio_libre#galeria5'
  get '/galeria6' => 'biblio_libre#galeria6'
  get '/galeria7' => 'biblio_libre#galeria7'
  get '/sociales' => 'biblio_libre#sociales'
  get '/batalla' => 'biblio_libre#batalla'
  get '/resultados' => 'biblio_libre#resultados'
  get '/about' => 'biblio_libre#about' # Borrar
  get '/about/manifest' => 'about#manifest', :as => 'manifest'
  get '/galerias' => 'biblio_libre#galerias'
  get '/comunidad' => 'biblio_libre#comunidad'
  get '/about/faqs' => 'about#faqs'
  get '/about/equipo' => 'about#equipo'
  get '/about/normas' => 'about#normas'
  get '/about/donaciones' => 'about#donaciones'
  get '/bibliocabinas' => 'biblio_libre#bibliocabinas'

  get '/diab' => 'biblio_libre#diab'
  post '/participa_diab' => 'diab#participa'

  post '/tinymce_assets' => 'biblio_libre#uploads'

  get '/massive_load' => 'biblio_libre#massive_load', :as => 'massive_load'
  post '/proccess_massive_load' => 'biblio_libre#proccess_massive_load', :as => 'proccess_massive_load'

  get '/vota/:battle_id/:book' => 'battles#vote'

  get '/books/export' => 'books#export_data'

  # get '/zohoverify/verifyforzoho.html', to: redirect('/assets/verifyforzoho.html')

  devise_for :users

  resources :releases
  resources :findings
  resources :books

  resources :battles

  get '/books/:code/ajax' => 'books#show_by_code', as: 'books_ajax'

  get '/check_code' => 'books#check_code'
  get '/new_book_and_finding/:code'  => 'books#new_book_and_finding', as: 'new_book_and_finding'
  get '/new_finding_with_code/:code' => 'findings#new_with_code', as: 'new_finding_with_code'


  get '/libera' => 'books#new_book_and_release', as: 'new_book_and_release'
  get '/new_book_and_release' => 'books#new_book_and_release'
  post '/printables' => 'books#printables', as: 'printables'
  post '/printables_diab' => 'diab#printables', as: 'printables_diab'
  get '/generate_pdf/:code' => 'books#generate_pdf', as: 'generate_pdf'

  get '/map' => 'findings#map', as: 'findings_map'

  get '/bibliotecas' => 'biblio_libre#bibliotecas', as: 'bibliotecas'
  get '/faq' => 'biblio_libre#faq', as: 'faq'
  get '/que_es' => 'biblio_libre#que_es', as: 'que_es'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
	match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'invitanos' => 'contact#invitanos', :as => 'invitanos', :via => :get
  match 'invitanos' => 'contact#invitanos_create', :as => 'invitanos', :via => :post

  match 'dona' => 'contact#dona', :as => 'dona', :via => :get
  match 'dona' => 'contact#dona_create', :as => 'dona', :via => :post

  match 'concurso' => 'contact#concurso', :as => 'concurso', :via => :get
  match 'concurso' => 'contact#concurso_create', :as => 'concurso', :via => :post

  get '/QR' => 'biblio_libre#index'
  get '/qr' => 'biblio_libre#index'

  get '/emails' => 'findings#emails'

  get '/nuevo_home' => 'biblio_libre#index_nuevo'

  get '/instrucciones' => 'biblio_libre#instrucciones', :as => 'instrucciones'

  get '/colaboradores' => 'biblio_libre#colaboradores', :as => 'colaboradores'

  get '/donativos' => 'biblio_libre#donativos', :as => 'donativos'

  get '/bibliolibre' => 'biblio_libre#index_nuevo', as: 'portada'

  root to: 'biblio_libre#index_nuevo'
  # root to: 'diab#index'
end

app/controllers/contact_controller.rb
# encoding: utf-8

class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    params[:message][:subject] = "[Contacto]  #{params[:message][:subject]}"
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Mensaje enviado correctamente.")
    else
      flash.now.alert = "Todos los campos son necesarios."
      render :new
    end
  end

  def invitanos
    @message = Message.new
  end

  def invitanos_create
    params[:message][:subject] = "[Invitanos] #{params[:message][:subject]}"
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Mensaje enviado correctamente.")
    else
      flash.now.alert = "Todos los campos son necesarios."
      render :invitanos
    end
  end

  def dona
    @message = Message.new
  end

  def dona_create
    params[:message][:subject] = "[Dona] #{params[:message][:subject]}"
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Mensaje enviado correctamente.")
    else
      flash.now.alert = "Todos los campos son necesarios."
      render :new
    end
  end

  def concurso
    @og_description = "¿Has soñado con tener súper poderes y salvar el mundo? ¿O hacerlo un poquito mejor de lo que es? En la Biblioteca Libre te invitamos a que revivas ese personaje que alguna vez imaginaste, aquel capaz de resolver los problemas de este planeta y combatir a los malvados. Gordos, flacos, chicos, gigantes, musculosos, enmascarados, encapuchados, humanos, alienígenas o mutantes. Todos son parte de este concurso."
    @og_title = "Concurso Literario: Se Busca al Nuevo Superhéroe del Mundo"

    @message = Message.new
  end

  def concurso_create
    params[:message][:subject] = "[Concurso]"
    @message = Message.new(params[:message])


    if @message.valid?
      NotificationsMailer.new_message_concurso(@message, params[:message][:document]).deliver
      NotificationsMailer.new_message_confirmacion(params[:message][:email], params[:message][:name]).deliver
      redirect_to(root_path, :notice => "Hemos recibido tu obra, muchas gracias por participar.")
    else
      flash.now.alert = "Todos los campos son necesarios."

      @og_description = "¿Has soñado con tener súper poderes y salvar el mundo? ¿O hacerlo un poquito mejor de lo que es? En la Biblioteca Libre te invitamos a que revivas ese personaje que alguna vez imaginaste, aquel capaz de resolver los problemas de este planeta y combatir a los malvados. Gordos, flacos, chicos, gigantes, musculosos, enmascarados, encapuchados, humanos, alienígenas o mutantes. Todos son parte de este concurso."
      @og_title = "Concurso Literario: Se Busca al Nuevo Superhéroe del Mundo"
      render :concurso
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/concurso.html.erb
<div class="row">
  <div class="span12">
    <img src="/assets/concurso22.png" alt="" />
  </div>
</div>
<br />

<%= form_for @message, url: concurso_path, html: {class: ""} do |form| %>

  <div class="row">
    <div class="span12">

      <div class="row">
        <div class="span12">

          <div class="row">
            <div class="span7">
              <br />
              <strong>Concurso Literario: Se Busca al Nuevo Superhéroe del Mundo</strong>
              <br /><br />
            </div>
            <div class="span5">
              <div class="fb-like pull-right" data-href="<%= request.original_url %>" data-layout="standard" data-action="recommend" data-show-faces="true" data-share="true"></div>
            </div>
          </div>
          <div class="row">
            <div class="span12">
              <p>¿Has soñado con tener súper poderes y salvar el mundo? ¿O hacerlo un poquito mejor de lo que es? En la Biblioteca Libre te invitamos a que revivas ese personaje que alguna vez imaginaste, aquel capaz de resolver los problemas de este planeta y combatir a los malvados. Gordos, flacos, chicos, gigantes, musculosos, enmascarados, encapuchados, humanos, alienígenas o mutantes. Todos son parte de este concurso.</p>

              <p>Son 5 páginas tamaño carta, como máximo de extensión, que puedes usar para contar la historia de tu superhéroe. Puedes hacerlo utilizando el género literario que más te guste.</p>

              <p>En todo caso, no te tomes mucho tiempo pues la fecha límite para recibir tu escrito vence, irrevocablemente, el viernes 31 de enero de 2014 a las 23:59 hrs.</p>

              <p>¿El premio? Los 10 textos más destacados serán ilustrados y publicados en un libro edición especial de la Biblioteca Libre.</p>

              <p>Llena el siguiente formulario con tus datos para poder concursar. No olvides adjuntar el archivo con tu texto. Además, aprovecha de revisar las <strong><a href="/assets/Bases Concurso Literario BL 2.pdf" target="_blank" style="color: #0055cc">bases</a></strong>  del concurso por si te queda alguna duda.</p>

              <p>Recuerda que siempre puedes contactar al equipo de la Biblioteca Libre por medio de biblioteca@catedraslibres.com en caso de consultas.</p>
              <br />
            </div>
          </div>
        </div>

      </div>

      <div class="well">
      <div class="row">
        <div class="span4">
          <label for="message_name">Nombre</label>
          <%= form.text_field :name, class: "span4", placeholder: "Nombre" %>
          <%= form.label :email %>
          <%= form.text_field :email, class: "span4", placeholder: "Correo" %>
          <label>Archivo</label>
          <%= form.file_field :document, class: "span4" %>
        </div>
        <div class="span7">
          <div class="row">
            <div class="span7">
              <label>Mensaje</label>
              <%= form.text_area :body, class: "input-xlarge span7", rows: 10 %>
            </div>
          </div>
          <div class="row">
            <div class="span7">
              <%= form.submit "Enviar", class: "btn btn-primary pull-right" %>
            </div>
          </div>
        </div>
      </div>

    </div>

    </div>

  </div>
<% end %>

app/views/contact/dona.html.erb
<%= form_for @message, url: dona_path, html: {class: ""} do |form| %>

<div class="row">
    <div class="span6">
        <img src="/assets/dona.jpg" alt="" />
    </div>
    <div class="span6">
        <row>
            <div class="span6">
                <p class="text-right">Con los libros que dones nos ayudarás a fomentar la lectura en Chile.</p>
                <p class="text-right">Desde 2018 hemos logrado distribuir gratuitamente más de 30.000 libros. Nuestra meta para este año son 40.000 libros. ¡Súmate!</p>
                <p class="text-right">Completa este formulario y nosotros los vamos a buscar a la puerta de tu casa:</p>
                <br />
            </div>
        </row>

        <div class="row">
            <div class="span6 well">
                <div class="row">
                    <div class="span6">
                        <h4>Envíanos un mensaje y coordinemos para ir a buscar los libros que quieres donar</h4>
                        <br />
                    </div>
                </div>
                <div class="row">
                    <div class="span6">
                        <label for="message_name">Nombre</label>
                        <%= form.text_field :name, class: "span4", placeholder: "Nombre" %>
                        <%= form.label :email %>
                        <%= form.text_field :email, class: "span4", placeholder: "Correo" %>
                        <label>Asunto</label>
                        <input class="span4" id="message_subject" name="message[subject]" type="hidden" value="Dona">
                    </div>
                </div>
                <div class="row">
                    <div class="span6">
                        <div class="row">
                            <div class="span6">
                                <label>Mensaje</label>
                                <%= form.text_area :body, class: "input-xlarge span6", rows: 10 %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="span6">
                                <%= form.submit "Enviar", class: "btn btn-primary pull-right" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<% end %>

app/views/contact/invitanos.html.erb
<%= form_for @message, url: invitanos_path, html: {class: ""} do |form| %>
  <div class="row">
    <div class="span8 offset2 well">
      <div class="row">
        <div class="span8">
          <h4>¡Invítanos y coordinemos una liberación de libros juntos!</h4>
          <br />
        </div>
      </div>
      <div class="row">
        <div class="span3">
          <%= form.label :name %>
          <%= form.text_field :name, class: "span3", placeholder: "Nombre" %>
          <%= form.label :email %>
          <%= form.text_field :email, class: "span3", placeholder: "Correo" %>
          <label>Asunto</label>
          <%= form.text_field :subject, class: "span3" %>
        </div>
        <div class="span4">
          <div class="row">
            <div class="span4">
              <label>Mensaje</label>
              <%= form.text_area :body, class: "input-xlarge span5", rows: 10 %>
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <%= form.submit "Enviar", class: "btn btn-primary pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contact/new.html.erb
<%= form_for @message, url: contact_path, html: {class: ""} do |form| %>
  <div class="row">
    <%= render 'about/menu' %>
    <br>
    <div class="span7 offset1 well">
      <div class="row">
        <div class="span7">
          <h4>¿Alguna duda o sugerencia? ¿Tienes libros en tu casa que quieras donar a nuestra biblioteca? Mándanos un mensaje y te responderemos a la brevedad.</h4>
          <br />
        </div>
      </div>
      <div class="row">
        <div class="span2">
          <%= form.label :name, 'Nombre' %>
          <%= form.text_field :name, class: "span2", placeholder: "Nombre" %>
          <%= form.label :email %>
          <%= form.text_field :email, class: "span2", placeholder: "Correo" %>
          <label>Asunto</label>
          <%= form.text_field :subject, class: "span2" %>
        </div>
        <div class="span3">
          <div class="row">
            <div class="span3">
              <label>Mensaje</label>
              <%= form.text_area :body, class: "input-xlarge span5", rows: 10 %>
            </div>
          </div>
          <div class="row">
            <div class="span3">
              <%= form.submit "Enviar", class: "btn btn-primary pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
<% end %>