config/routes.rb
BiblioLibre::Application.routes.draw do

  resources :posts
  resources :hearts, only: :create

  get '/diab_portada' => 'diab#index', as: 'diab'

  get 'tags/:tag' => 'posts#comunidad', as: :tag
  get '/posts/comunidad' => 'posts#comunidad'
  get '/comunidad' => 'posts#comunidad', as: 'comunidad'
  get '/noticias/1' => 'biblio_libre#noticia1', :as => 'noticia1'
  get '/noticias/2' => 'biblio_libre#noticia2', :as => 'noticia2'
  get '/noticias/3' => 'biblio_libre#noticia3', :as => 'noticia3'
  get '/noticias/4' => 'biblio_libre#noticia4', :as => 'noticia4'
  get '/noticias/5' => 'biblio_libre#noticia5', :as => 'noticia5'
  get '/noticias/:id' => 'posts#noticia'
  get '/galeria1' => 'biblio_libre#galeria1'
  get '/galeria2' => 'biblio_libre#galeria2'
  get '/galeria3' => 'biblio_libre#galeria3'
  get '/galeria4' => 'biblio_libre#galeria4'
  get '/galeria5' => 'biblio_libre#galeria5'
  get '/galeria6' => 'biblio_libre#galeria6'
  get '/galeria7' => 'biblio_libre#galeria7'
  get '/sociales' => 'biblio_libre#sociales'
  get '/batalla' => 'biblio_libre#batalla'
  get '/resultados' => 'biblio_libre#resultados'
  get '/about' => 'biblio_libre#about' # Borrar
  get '/about/manifest' => 'about#manifest', :as => 'manifest'
  get '/galerias' => 'biblio_libre#galerias'
  get '/comunidad' => 'biblio_libre#comunidad'
  get '/about/faqs' => 'about#faqs'
  get '/about/equipo' => 'about#equipo'
  get '/about/normas' => 'about#normas'
  get '/about/donaciones' => 'about#donaciones'
  get '/bibliocabinas' => 'biblio_libre#bibliocabinas'

  get '/diab' => 'biblio_libre#diab'
  post '/participa_diab' => 'diab#participa'

  post '/tinymce_assets' => 'biblio_libre#uploads'

  get '/massive_load' => 'biblio_libre#massive_load', :as => 'massive_load'
  post '/proccess_massive_load' => 'biblio_libre#proccess_massive_load', :as => 'proccess_massive_load'

  get '/vota/:battle_id/:book' => 'battles#vote'

  get '/books/export' => 'books#export_data'

  # get '/zohoverify/verifyforzoho.html', to: redirect('/assets/verifyforzoho.html')

  devise_for :users

  resources :releases
  resources :findings
  resources :books

  resources :battles

  get '/books/:code/ajax' => 'books#show_by_code', as: 'books_ajax'

  get '/check_code' => 'books#check_code'
  get '/new_book_and_finding/:code'  => 'books#new_book_and_finding', as: 'new_book_and_finding'
  get '/new_finding_with_code/:code' => 'findings#new_with_code', as: 'new_finding_with_code'


  get '/libera' => 'books#new_book_and_release', as: 'new_book_and_release'
  get '/new_book_and_release' => 'books#new_book_and_release'
  post '/printables' => 'books#printables', as: 'printables'
  post '/printables_diab' => 'diab#printables', as: 'printables_diab'
  get '/generate_pdf/:code' => 'books#generate_pdf', as: 'generate_pdf'

  get '/map' => 'findings#map', as: 'findings_map'

  get '/bibliotecas' => 'biblio_libre#bibliotecas', as: 'bibliotecas'
  get '/faq' => 'biblio_libre#faq', as: 'faq'
  get '/que_es' => 'biblio_libre#que_es', as: 'que_es'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
	match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'invitanos' => 'contact#invitanos', :as => 'invitanos', :via => :get
  match 'invitanos' => 'contact#invitanos_create', :as => 'invitanos', :via => :post

  match 'dona' => 'contact#dona', :as => 'dona', :via => :get
  match 'dona' => 'contact#dona_create', :as => 'dona', :via => :post

  match 'concurso' => 'contact#concurso', :as => 'concurso', :via => :get
  match 'concurso' => 'contact#concurso_create', :as => 'concurso', :via => :post

  get '/QR' => 'biblio_libre#index'
  get '/qr' => 'biblio_libre#index'

  get '/emails' => 'findings#emails'

  get '/nuevo_home' => 'biblio_libre#index_nuevo'

  get '/instrucciones' => 'biblio_libre#instrucciones', :as => 'instrucciones'

  get '/colaboradores' => 'biblio_libre#colaboradores', :as => 'colaboradores'

  get '/donativos' => 'biblio_libre#donativos', :as => 'donativos'

  get '/bibliolibre' => 'biblio_libre#index_nuevo', as: 'portada'

  root to: 'biblio_libre#index_nuevo'
  # root to: 'diab#index'
end

app/views/layouts/admin.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "La Biblioteca Libre" %></title>
  <meta name="description" content="La Biblioteca Libre">
  <meta name="author" content="La Biblioteca Libre">

  <meta property="og:title" content="La Biblioteca Libre"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://www.labibliotecalibre.cl/"/>
  <meta property="og:description" content="La Biblioteca Libre es una iniciativa que promueve el intercambio gratuito de libros: las personas dejan o toman ejemplares de su interés. Los libros de La Biblioteca Libre no son de nadie en particular y son de todos en general. Una vez que leas los libros no los dejes en tu casa juntando polvo, pásalos a alguien más, que sigan su rumbo por el mundo." />
  <meta property="og:image" content="http://www.labibliotecalibre.cl/assets/lbl.jpg" />
  <meta property="og:image:type" content="image/jpg" />
  <meta property="og:image:width" content="600" />
  <meta property="og:image:height" content="600" />


  <link rel="shortcut icon" href="/assets/favicon.ico" />
  <%= stylesheet_link_tag "nuevo", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-41898970-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body>
<div class="container">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
<div class="row">
  <div id="wrapper" class="span12">
    <div class="masthead">
      <ul class="nav nav-pills pull-right botones">
        <li><%= link_to('Inicio', root_path) %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Proyecto<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <!-- <li><a href="#">Manifiesto</a></li> -->
            <li><%= link_to('Preguntas frecuentes', faq_path) %></li>
            <!-- <li><a href="#">Equipo</a></li> -->
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Liberaciones<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to('¿Qué es?', que_es_path) %></li>
            <!-- <li><a href="#">Calendario</a></li> -->
            <li><%= link_to('Invítanos', invitanos_path) %></li>
          </ul>
        </li>
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">+ Libros<b class="caret"></b></a>
         <ul class="dropdown-menu">
           <!-- <li><a href="#">Puntos de lectura</a></li> -->
           <li><%= link_to('Bibliotecas amigas', bibliotecas_path) %></li>
         </ul>
       </li>
       <li><%= link_to('Contacto', contact_path) %></li>
     </ul>
     <a href='<%= root_path %>'><img id="logo" src='/assets/BL_apaisado-03.png' height='70px' /></a>
   </div>
   <!-- <hr /> -->
 </div>

  <div class="span12">
    <% [:notice, :error, :alert].each do |level| %>
      <% unless flash[level].blank? %>
        <div class="alert alert-message alert-<%= flash_class(level) %>">
          <%= content_tag :p, flash[level] %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="span12">
  <%= yield %>
 </div>

  <div class="span12">
    <div class="row">
      <div class="span12">
        <!-- <hr /> -->
        <br />
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <div class="well">
          <div class="row">
            <div class="span4">
              <a href="http://catedraslibres.org/"><img src="/assets/catedras.png" /></a>
            </div>
            <div class="span3">
              <p>La Biblioteca Libre</p>
              <p>Email: biblioteca@catedraslibres.cl</p>
              <br />
            </div>
            <div class="span4">
              <div class="row">
                <div class="span4">
                  <p class="credit" style="">Nuestros colaboradores:</p>
                </div>
              </div>
              <div class="row">
              <div class="span4">
                  <img src="/assets/gam.png" style="height:60px; margin-right: 3px;" />
                  <img src="/assets/muni_stgo_bk.png" style="height:60px" />
                  <img src="/assets/startup_bk.png" style="width: 140px" />
                  <img src="/assets/fau_bk.png" style="height:60px" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCjFGRwHIUl0nLB59JL-4bWR-w2qc1auqo&sensor=true" %>
</div>
</body>
</head>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script>
    tinymce.init({selector:'textarea.tiny'});
    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "La Biblioteca Libre" %></title>
    <meta name="description" content="La Biblioteca Libre es una biblioteca colectiva creada con los aportes de miles de libros de cientos de personas, para que éstos sean compartidos gratuita y libremente entre todos y no se pierdan en los hogares sin que nadie los lea.">
    <meta name="author" content="La Biblioteca Libre" />
    <% if @og_title %>
    <meta property="og:title" content="<%= @og_title %>"/>
    <% else %>
    <meta property="og:title" content="La Biblioteca Libre"/>
    <% end %>
    <% if @og_title %>
    <meta property="og:url" content="<%= request.original_url %>"/>
    <% else %>
    <meta property="og:url" content="http://www.labibliotecalibre.cl/"/>
    <% end %>
    <% if @og_description %>
    <meta property="og:description" content="<%= @og_description %>" />
    <% else %>
    <meta property="og:description" content="La Biblioteca Libre es una iniciativa que promueve el intercambio gratuito de libros: las personas dejan o toman ejemplares de su interés. Los libros de La Biblioteca Libre no son de nadie en particular y son de todos en general. Una vez que leas los libros no los dejes en tu casa juntando polvo, pásalos a alguien más, que sigan su rumbo por el mundo." />
    <% end %>
    <% if @og_image %>
    <meta property="og:image" content="<%= @og_image %>" />
    <meta property="og:image:width" content="320" />
    <meta property="og:image:height" content="222" />
    <% else %>
    <meta property="og:image" content="http://www.labibliotecalibre.cl/assets/lbl2.jpg" />
    <meta property="og:image:type" content="image/jpg" />
    <meta property="og:image:width" content="333" />
    <meta property="og:image:height" content="333" />
    <% end %>
    <meta property="og:type" content="website"/>
    <link rel="shortcut icon" href="https://s3.amazonaws.com/bibliorock/favicon.ico" />
    <%= stylesheet_link_tag "nuevo", :media => "all" %>
    <%= csrf_meta_tags %>
    <br />
    <%= yield(:head) %>
    <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-41898970-1']);
    _gaq.push(['_trackPageview']);
    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>
  </head>
  <body>
    <script type="text/javascript">
    <!--
    function toggle_visibility(id) {
    var e = document.getElementById(id);
    if(e.style.display == 'block')
    e.style.display = 'none';
    else
    e.style.display = 'block';
    }
    //-->
    </script>
    <div class="container">
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=1391896011060426";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
      </script>
      <div class="row">
        <div id="wrapper" class="span12">
          <div class="masthead">
            <ul class="nav nav-pills pull-right botones" style="font-size: 14px">
              <li><%= link_to('Inicio', root_path) %></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Liberaciones<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="http://www.labibliotecalibre.cl/posts/que-es-una-liberacion-de-libros/">¿Qué es?</a></li>
                  <!-- <li><a href="#">Calendario</a></li> -->
                  <li><%= link_to('Invítanos', invitanos_path) %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">+ Libros<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <!-- <li><a href="#">Puntos de lectura</a></li> -->
                  <li><%= link_to('Bibliotecas amigas', bibliotecas_path) %></li>
                </ul>
              </li>
              <li><%= link_to('Colaboradores', colaboradores_path) %></li>
              <li><%= link_to('Proyecto', '/about/manifest') %></li>
            </ul>
            <a href='<%= root_path %>'><img id="logo" src='/assets/BL_apaisado-03.png' height='70px' /></a>
          </div>
          <!-- <hr /> -->
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <% [:notice, :error, :alert].each do |level| %>
          <% unless flash[level].blank? %>
          <div class="alert alert-message alert-<%= flash_class(level) %>">
            <%= content_tag :p, flash[level] %>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <br /><br />
          <%= yield %>
        </div>
      </div>
      <div class="row">
        <br /><br />
        <div class="span12">
          <div class="well">
          <div class="row margin-footer">
            <div class="span3" style="margin-left: 24px;">
              <br />
              <a href="http://catedraslibres.org/"><img src="/assets/catedras.png" style="margin-top:0px"/></a>
            </div>
            <div class="span3">
              <p>La Biblioteca Libre</p>
              <p>Email: biblioteca@catedraslibres.com</p>
              <br />
            </div>
            <div class="span3">
              <!-- Begin MailChimp Signup Form -->
              <div id="mc_embed_signup">
                <form action="//facebook.us5.list-manage.com/subscribe/post?u=571489017f07d1eabe0f0bc13&amp;id=7eb851951a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                  <label for="mce-EMAIL">Suscríbete a nuestra lista de correo</label>
                  <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Correo electrónico" required>
                  <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                  <div style="position: absolute; left: -5000px;"><input type="text" name="b_571489017f07d1eabe0f0bc13_7eb851951a" tabindex="-1" value=""></div>
                  <div class="clear"><input type="submit" value="Suscribirme" name="subscribe" id="mc-embedded-subscribe" class="btn"></div>
                </form>
              </div>
              <!--End mc_embed_signup-->
            </div>
            <div class="span3">
              <div class="row">
                <div class="span3">
                  <div class="fb-like-box" data-href="https://www.facebook.com/labibliotecalibre" data-width="100%" data-show-faces="false" data-header="false" data-stream="false" data-show-border="true"></div>
                </div>
              </div>
            </div>
          </div>

          </div> <!-- well -->

        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCjFGRwHIUl0nLB59JL-4bWR-w2qc1auqo&sensor=true" %>
    <script src="http://code.highcharts.com/highcharts.js"></script>
  </div>
</body>
</html>

app/views/layouts/diab.html.haml
!!!
%html
  %head
    %title Diab
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{:content => "La Biblioteca Libre es una biblioteca colectiva creada con los aportes de miles de libros de cientos de personas, para que éstos sean compartidos gratuita y libremente entre todos y no se pierdan en los hogares sin que nadie los lea.", :name => "description"}/

    %title= content_for?(:title) ? yield(:title) : "Día B - La Biblioteca Libre"
    %meta{:content => "La Biblioteca Libre", :name => "author"}/
    - if @og_title
      %meta{:content => @og_title, :property => "og:title"}/
    - else
      %meta{:content => "La Biblioteca Libre", :property => "og:title"}/
    - if @og_title
      %meta{:content => request.original_url, :property => "og:url"}/
    - else
      %meta{:content => "http://www.labibliotecalibre.cl/", :property => "og:url"}/
    - if @og_description
      %meta{:content => @og_description, :property => "og:description"}/
    - else
      %meta{:content => "La Biblioteca Libre es una iniciativa que promueve el intercambio gratuito de libros: las personas dejan o toman ejemplares de su interés. Los libros de La Biblioteca Libre no son de nadie en particular y son de todos en general. Una vez que leas los libros no los dejes en tu casa juntando polvo, pásalos a alguien más, que sigan su rumbo por el mundo.", :property => "og:description"}/
    - if @og_image
      %meta{:content => @og_image, :property => "og:image"}/
      %meta{:content => "320", :property => "og:image:width"}/
      %meta{:content => "222", :property => "og:image:height"}/
    - else
      %meta{:content => "http://www.labibliotecalibre.cl/assets/lbl2.jpg", :property => "og:image"}/
      %meta{:content => "image/jpg", :property => "og:image:type"}/
      %meta{:content => "333", :property => "og:image:width"}/
      %meta{:content => "333", :property => "og:image:height"}/
    %meta{:content => "website", :property => "og:type"}/
    %link{:href => "https://s3.amazonaws.com/bibliorock/favicon.ico", :rel => "shortcut icon"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-41898970-1']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  %body.diab
    = render 'diab/menu'
    = yield
    = javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCjFGRwHIUl0nLB59JL-4bWR-w2qc1auqo&sensor=true"
    %script{:src => "http://code.highcharts.com/highcharts.js"}

app/views/layouts/viejo.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "La Biblioteca Libre" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-41898970-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  </script>
  </head>
  <body>
  <div id="wrap">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <div class="pull-left">
            <a href='<%= root_path %>'><img id="logo" src="/assets/logo_30px.png" style="height: 25px; margin-top: 5px;" alt="La Biblioteca Libre"/></a>
          </div>
          <a href="#" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse collapse">
            <div class="nav pull-right">
                <li class="divider-vertical"></li>
                <li><%= link_to('Preguntas frecuentes', faq_path) %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to('Bibliotecas amigas', bibliotecas_path) %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to('Contacto', contact_path) %></li>
                <li class="divider-vertical"></li>
                <li><div class="fb-like pull-right" data-href="http://www.facebook.com/labibliotecalibre" data-send="false" data-layout="button_count" data-width="50" data-show-faces="false" style="margin-top: 8px;"></div></li>
                <% if  user_signed_in? %>
                  <li><%= link_to('Salir', destroy_user_session_path, method: :delete) %></li>
                <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div> <!-- class="content"> -->

          <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
              <div class="alert alert-message alert-<%= flash_class(level) %>">
                <a class="close" href="#">×</a>
                <%= content_tag :p, flash[level] %>
              </div>
            <% end %>
          <% end %>
              <%= yield %>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->

     <div id="push"></div>

    </div>

    <div id="footer">
      <div class="container">
        <div class="row negro pull-right">
          <div class="span4">
            <div class="row">
              <p class="muted credit pull-left" style="margin-top: 30px; vertical-align: middle;">Nuestros patrocinadores:</p>
            </div>
            <div class="row">
              <div class="span2 offset1">
                <img class="center" src="/assets/muni_stgo.png" style="height:60px; margin-right: 30px;" />
              </div>
            </div>
          </div>
          <div class="span4">
            <div class="row">
              <p class="muted credit pull-left" style="margin-top: 30px; vertical-align: middle;">Nuestros colaboradores:</p>
            </div>
            <div class="row">
              <img class="pull-right" src="/assets/startup.png" style="width: 140px; margin-top: 25px; margin-right: 30px;" />
              <img class="pull-right" src="/assets/fau.png" style="height:60px; margin-right: 30px;" />
            </div>
          </div>
        </div>
      </div>
     </div>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCjFGRwHIUl0nLB59JL-4bWR-w2qc1auqo&sensor=true" %>
  </body>
</html>